---
title: "Country information"
author: "Stephanie Rivera"
date: "5/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(maps)
library(geosphere)
library(rgeos)
library(rworldmap)
library(data.table)
```


```{r cars}
country_data <- read.csv(file = "emails.country.csv", header= TRUE, sep=",")
```

## Plots to show distribution of authors throughout different countries

You can also embed plots, for example:

```{r pressure, echo=FALSE}

country_data$Serial <- rep(1,nrow(country_data))

#country_data[country_data == "Russian Federation"] <- "Russia"

#ifelse(country_data$Name == "Russian Federation", "Russia", NA)

#aggregate by country to get a count 
count_country <- aggregate(country_data$Serial,by=list(Name=country_data$Name), FUN=sum)
#count_country <- count_country[order(-count_country$x),]
colnames(count_country) <- c("Country", "count")

#filter for countries with counts of at least 1000

count_country <- count_country %>% filter(count > 50)

a <- ggplot(count_country, aes(x = reorder(Country, count), y = count, fill=count)) + geom_bar(stat= "identity")+ theme(axis.text.x = element_text(angle = 90, hjust = 1)) + scale_fill_gradient(low = "red", high = "green") + ggtitle("Country Counts for Article Contributors") + xlab(label = "Countries (count > 50)") + ylab(label = "Count") + coord_flip() 
a 

```





